version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DATABASE_URL=postgres://ufnfau5kv8ccm3:p894c361b36f67849f2d2a8d42f7f9925a4b4544a21c08dbd29ca1c0d8a3149ce@c2v3jin4rntblb.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dfbe1so4u5iaqt
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5002
